Repository GSA/notifications-api, pull requests merged in 2024-04, with the labels that each got.

#891 Revert recent Terraform changes to prod and demo
  terraform/demo/main.tf
  terraform/demo/providers.tf
  terraform/production/main.tf
  terraform/production/providers.tf
Labels: engineering

#893 Revert the rest of our Terraform changes
  terraform/bootstrap/providers.tf
  terraform/development/main.tf
  terraform/development/providers.tf
  terraform/sandbox/main.tf
  terraform/sandbox/providers.tf
  terraform/shared/egress_space/main.tf
  terraform/shared/egress_space/providers.tf
  terraform/shared/egress_space/variables.tf
  terraform/shared/ses/main.tf
  terraform/shared/ses/providers.tf
  terraform/shared/ses/variables.tf
  terraform/shared/sns/main.tf
  terraform/shared/sns/providers.tf
  terraform/shared/sns/variables.tf
  terraform/staging/main.tf
  terraform/staging/providers.tf
Labels: engineering

#895 Mirror admin repo poetry updates
  Makefile
  pyproject.toml
Labels: engineering, dependencies

#897 Update GitHub Actions
  .github/workflows/adr-accepted.yml
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .github/workflows/drift.yml
  .github/workflows/terraform-demo.yml
  .github/workflows/terraform-production.yml
  .github/workflows/terraform-staging.yml
  poetry.lock
Labels: engineering, security, dependencies

#905 Update utils to 0.4.5
  poetry.lock
Labels: engineering, dependencies

#913 Added ability for poetry to add and delete the test_notifications_api db during tests for #598
  poetry.lock
  pyproject.toml
  tests/conftest.py
Labels: engineering, dependencies, python

#918 Update utils to 0.4.6
  poetry.lock
  test_csv_files/multiple_sms.csv
  test_csv_files/sms.csv
  tests/app/celery/test_tasks.py
  tests/app/notifications/test_process_notification.py
  tests/app/notifications/test_validators.py
  tests/app/service/send_notification/test_send_notification.py
  tests/app/service/send_notification/test_send_one_off_notification.py
  tests/app/service/test_rest.py
  tests/app/test_model.py
  tests/app/test_schemas.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: engineering, dependencies

#924 Updated dependencies and ignore gunicorn audit flag
  .github/workflows/checks.yml
  poetry.lock
Labels: engineering, security, dependencies

#929 04/17/2024 Production Deploy
  .github/workflows/checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  app/celery/scheduled_tasks.py
  app/commands.py
  app/config_files/templates.json
  poetry.lock
  pyproject.toml
  terraform/README.md
  terraform/bootstrap/main.tf
  test_csv_files/multiple_sms.csv
  test_csv_files/sms.csv
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/notifications/test_process_notification.py
  tests/app/notifications/test_validators.py
  tests/app/service/send_notification/test_send_notification.py
  tests/app/service/send_notification/test_send_one_off_notification.py
  tests/app/service/test_rest.py
  tests/app/test_model.py
  tests/app/test_schemas.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
  tests/app/v2/notifications/test_post_notifications.py
  tests/conftest.py
Labels: engineering

#930 Update gunicorn to latest release
  .github/workflows/checks.yml
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#935 04/18/2024 Production Deploy
  .github/workflows/checks.yml
  app/config.py
  app/dao/users_dao.py
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies

#949 4/26/2024 Production Deploy
  README.md
  app/organization/invite_rest.py
  app/service/rest.py
  app/service_invite/rest.py
  poetry.lock
  terraform/README.md
  terraform/bootstrap/main.tf
  terraform/bootstrap/providers.tf
  terraform/demo/providers.tf
  terraform/development/providers.tf
  terraform/production/providers.tf
  terraform/sandbox/main.tf
  terraform/sandbox/providers.tf
  terraform/shared/egress_space/providers.tf
  terraform/shared/ses/providers.tf
  terraform/shared/sns/providers.tf
  terraform/staging/providers.tf
  tests/app/service_invite/test_service_invite_rest.py
Labels: engineering
