Repository GSA/notifications-api, pull requests merged in 2024-05, with the labels that each got.

#946 Code changes for SQLAlchemy 2.0.x upgrade
  Makefile
  app/commands.py
  app/dao/dao_utils.py
  app/dao/fact_billing_dao.py
  app/dao/fact_notification_status_dao.py
  app/dao/fact_processing_time_dao.py
  app/dao/inbound_sms_dao.py
  app/dao/notifications_dao.py
  app/dao/permissions_dao.py
  app/dao/service_user_dao.py
  app/dao/services_dao.py
  app/dao/users_dao.py
  app/history_meta.py
  app/service_invite/rest.py
  app/status/healthcheck.py
  app/user/rest.py
  migrations/versions/0021_add_delivered_failed_counts.py
  migrations/versions/0025_notify_service_data.py
  migrations/versions/0039_fix_notifications.py
  migrations/versions/0045_billable_units.py
  migrations/versions/0095_migrate_existing_svc_perms.py
  migrations/versions/0096_update_job_stats.py
  migrations/versions/0112_add_start_end_dates.py
  migrations/versions/0237_add_filename_to_dvla_org.py
  migrations/versions/0246_notifications_index.py
  migrations/versions/0303_populate_services_org_id.py
  migrations/versions/0308_delete_loadtesting_provider.py
  migrations/versions/0312_populate_returned_letters.py
  migrations/versions/0328_international_letters_perm.py
  migrations/versions/0331_add_broadcast_org.py
  migrations/versions/0345_move_broadcast_provider.py
  migrations/versions/0348_migrate_broadcast_settings_migrate_broadcast_settings.py
  migrations/versions/0374_fix_reg_template_history.py
  migrations/versions/0395_remove_intl_letters_perm.py
  poetry.lock
  pyproject.toml
  tests/app/dao/test_fact_billing_dao.py
  tests/conftest.py
Labels: engineering, dependencies

#1010 Add missing dependencies
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python

#1011 Update pre-commit hooks
  .ds.baseline
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: engineering, security, dependencies

#1042 Fix debug statement
  app/service/rest.py
Labels: engineering, python
