Repository GSA/notifications-api, pull requests merged in 2024-03, with the labels that each got.

#826 Add E2E configuration information to docs
  README.md
  docs/all.md
Labels: documentation, engineering

#829 Removed gov.uk text from org invite
  app/organization/invite_rest.py
  tests/app/organization/test_invite_rest.py
Labels: engineering, bug

#849 Fix remaining Terraform for production and demo
  terraform/demo/main.tf
  terraform/demo/providers.tf
  terraform/production/main.tf
  terraform/production/providers.tf
  terraform/shared/egress_space/main.tf
  terraform/shared/egress_space/variables.tf
Labels: engineering

#846 API Production Deploy 3/14/2023
  .github/workflows/checks.yml
  Makefile
  README.md
  app/aws/s3.py
  app/celery/provider_tasks.py
  app/dao/notifications_dao.py
  app/dao/users_dao.py
  app/delivery/send_to_providers.py
  app/job/rest.py
  app/models.py
  app/notifications/process_notifications.py
  app/notifications/rest.py
  app/organization/invite_rest.py
  app/organization/rest.py
  app/service/rest.py
  app/service_invite/rest.py
  app/user/rest.py
  app/v2/notifications/get_notifications.py
  migrations/versions/0410_enums_for_everything.py
  migrations/versions/0411_add_login_uuid.py
  terraform/bootstrap/providers.tf
  terraform/demo/main.tf
  terraform/demo/providers.tf
  terraform/development/main.tf
  terraform/development/providers.tf
  terraform/production/main.tf
  terraform/production/providers.tf
  terraform/sandbox/main.tf
  terraform/sandbox/providers.tf
  terraform/shared/egress_space/main.tf
  terraform/shared/egress_space/providers.tf
  terraform/shared/egress_space/variables.tf
  terraform/shared/ses/main.tf
  terraform/shared/ses/providers.tf
  terraform/shared/ses/variables.tf
  terraform/shared/sns/main.tf
  terraform/shared/sns/providers.tf
  terraform/shared/sns/variables.tf
  terraform/staging/main.tf
  terraform/staging/providers.tf
  tests/app/aws/test_s3.py
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_service_callback_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/dao/test_users_dao.py
  tests/app/db.py
  tests/app/delivery/test_send_to_providers.py
  tests/app/job/test_rest.py
  tests/app/notifications/test_rest.py
  tests/app/public_contracts/test_GET_notification.py
  tests/app/service/test_rest.py
  tests/app/service_invite/test_service_invite_rest.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
  tests/app/v2/notifications/test_get_notifications.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: engineering

#857 Update utils to 0.3.0
  poetry.lock
Labels: engineering, dependencies

#860 Remove debug lines in CSV processing
  app/aws/s3.py
Labels: engineering

#861 Adjust production worker memory to 1G
  deploy-config/production.yml
Labels: engineering

#859 API Production Deploy - 3/19/2024
  app/__init__.py
  app/aws/s3.py
  app/service/utils.py
  deploy-config/production.yml
  poetry.lock
  pyproject.toml
  tests/app/notifications/test_validators.py
Labels: engineering

#867 Update Cloud Foundry runtime.txt file
  runtime.txt
Labels: engineering
