Repository GSA/notifications-api, pull requests merged in 2024-12, with the labels that each got.

#1451 12/2/24 - 12/3/24 Production Deploy - DB insert retry and go live email fixes
  app/celery/provider_tasks.py
  app/celery/tasks.py
  app/service/sender.py
  tests/app/service/test_sender.py
Labels: engineering, python

#1456 Update restage workflow to use latest cg-cli-tools
  .github/workflows/restage-apps.yml
Labels: engineering, github_actions

#1458 Bump production Redis plan to 5node-large
  terraform/production/main.tf
Labels: engineering

#1460 12/4/2024 Production Deploy - large batch hotfixes
  .github/workflows/restage-apps.yml
  app/celery/tasks.py
  app/dao/notifications_dao.py
  app/notifications/process_notifications.py
  terraform/production/main.tf
Labels: engineering, python

#1461 Revert Redis plan back
  terraform/production/main.tf
Labels: engineering

#1462 12/4/2024 Production Deploy Hotfix 2
  app/celery/process_ses_receipts_tasks.py
  app/celery/provider_tasks.py
  app/celery/tasks.py
  app/config.py
  terraform/production/main.tf
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_tasks.py
Labels: engineering

#1475 12/11/2024 Production Deployment API hotfixes
  app/celery/provider_tasks.py
  app/clients/cloudwatch/aws_cloudwatch.py
  app/config.py
Labels: engineering, python

#1477 Revert previous hotfixes
  app/celery/provider_tasks.py
  app/clients/cloudwatch/aws_cloudwatch.py
  app/config.py
Labels: engineering, python

#1478 12/12/2024 Production Deploy
  app/celery/provider_tasks.py
  app/clients/cloudwatch/aws_cloudwatch.py
  app/config.py
  migrations/versions/0413_add_message_id.py
Labels: engineering, python

#1483 Production Deploy 12/12/24 - small retry hotfix
  app/celery/tasks.py
Labels: engineering, python

#1498 Bump jinja2 from 3.1.4 to 3.1.5 to address vulnerability
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies
