Repository GSA/notifications-api, pull requests merged in 2024-07, with the labels that each got.

#1151 Attempt to prevent poetry.lock from constantly changing
  poetry.lock
Labels: engineering, dependencies, python

#1149 Update pull request template and docs
  .github/pull_request_template.md
  README.md
  docs/all.md
Labels: documentation, engineering

#1156 07/02/2024 Production Release
  .github/pull_request_template.md
  README.md
  app/commands.py
  docs/all.md
  notifications_utils/recipients.py
  poetry.lock
  pyproject.toml
  tests/app/service/send_notification/test_send_notification.py
  tests/app/user/test_rest.py
  tests/notifications_utils/test_recipient_validation.py
Labels: engineering

#1163 07/03/2024 Production Release
  app/commands.py
  docs/all.md
  poetry.lock
  pyproject.toml
Labels: engineering

#1059 1006/1007/1008 created new API endpoints for front end statistics
  app/dao/date_util.py
  app/dao/fact_notification_status_dao.py
  app/dao/services_dao.py
  app/service/rest.py
  app/service/statistics.py
  migrations/versions/0025_notify_service_data.py
  migrations/versions/0028_fix_reg_template_history.py
  migrations/versions/0082_add_golive_template.py
  migrations/versions/0117_international_sms_notify.py
  migrations/versions/0134_add_email_2fa_template_.py
  migrations/versions/0139_migrate_sms_allowance_data.py
  migrations/versions/0171_add_org_invite_template.py
  migrations/versions/0265_add_confirm_edit_templates.py
  migrations/versions/0294_add_verify_reply_to_.py
  migrations/versions/0330_broadcast_invite_email.py
  migrations/versions/0347_add_dvla_volumes_template.py
  migrations/versions/0401_add_e2e_test_user.py
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/service/test_statistics.py
  tests/app/service/test_statistics_rest.py
Labels: engineering, python

#1171 07/05/2024 Production Deploy
  app/dao/date_util.py
  app/dao/fact_notification_status_dao.py
  app/dao/services_dao.py
  app/dao/users_dao.py
  app/service/rest.py
  app/service/statistics.py
  app/user/rest.py
  docs/all.md
  migrations/versions/0025_notify_service_data.py
  migrations/versions/0028_fix_reg_template_history.py
  migrations/versions/0082_add_golive_template.py
  migrations/versions/0117_international_sms_notify.py
  migrations/versions/0134_add_email_2fa_template_.py
  migrations/versions/0139_migrate_sms_allowance_data.py
  migrations/versions/0171_add_org_invite_template.py
  migrations/versions/0265_add_confirm_edit_templates.py
  migrations/versions/0294_add_verify_reply_to_.py
  migrations/versions/0330_broadcast_invite_email.py
  migrations/versions/0347_add_dvla_volumes_template.py
  migrations/versions/0401_add_e2e_test_user.py
  poetry.lock
  pyproject.toml
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/service/test_statistics.py
  tests/app/service/test_statistics_rest.py
Labels: engineering

#1186 07/16/2024 Production Deploy
  .ds.baseline
  app/dao/services_dao.py
  app/user/rest.py
  docs/all.md
  poetry.lock
  pyproject.toml
  terraform/README.md
  tests/app/dao/test_services_dao.py
Labels: engineering

#1204 Increased API and worker app memory to 4GB
  deploy-config/production.yml
Labels: engineering

#1210 Update Python runtime version for cloud.gov
  runtime.txt
Labels: engineering, python

#1213 Adjust production manifest settings
  deploy-config/production.yml
Labels: engineering

#1214 7/25/2024 Follow-up production release
  deploy-config/production.yml
Labels: engineering

#1220 7/29/2024 Production Deploy for logging improvements
  app/celery/nightly_tasks.py
Labels: engineering

#1225 Update Python dependencies - 7/30/24
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, python
