Repository GSA/notifications-api, pull requests merged in 2024-06, with the labels that each got.

#1054 API-1044 - Fixing the test to be less fragile.
  tests/app/dao/test_service_sms_sender_dao.py
Labels: bug

#1106 Fix runtime.txt for cloud.gov and Python
  runtime.txt
Labels: engineering, python

#1111 Increased production memory to 2 GB
  deploy-config/production.yml
Labels: engineering

#1124 06/26/2024 Production Deploy #2
  manifest.yml
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: engineering

#1126 06/26/2024 Production Deploy #3
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
Labels: engineering

#1128 06/26/2024 Production Release #4
  manifest.yml
  terraform/production/main.tf
Labels: engineering

#1138 06/27/2024 Production Deploy
  terraform/demo/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: engineering
