Repository GSA/notifications-api, pull requests merged in 2025-05, with the labels that each got.

#1693 Pin virtualenv to a compatible version
  .github/actions/setup-project/action.yml
  Makefile
  poetry.lock
  pyproject.toml
Labels: engineering, dependencies, github_actions

#1697 Update no_proxy and S3 error handling
  .profile
  app/aws/s3.py
Labels: engineering

#1695 05/07/2025 Production Deploy
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
  .github/actions/setup-project/action.yml
  .profile
  Makefile
  README.md
  app/aws/s3.py
  app/celery/tasks.py
  app/clients/cloudwatch/aws_cloudwatch.py
  docs/all.md
  poetry.lock
  pyproject.toml
Labels: engineering

#1729 05/22/2025 Production Deploy
  .github/dependabot.yml
  README.md
  app/__init__.py
  app/aws/s3.py
  app/service/rest.py
  app/socket_handlers.py
  docs/openapi.yml
  poetry.lock
  pyproject.toml
  tests/app/aws/test_s3.py
Labels: engineering

#1743 Updated pip-audit ignore-vulns
  .ds.baseline
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
Labels: engineering, dependencies, python

#1747 Remove extra vulnerability from our ignore list
  .github/workflows/checks.yml
Labels: engineering
