Repository GSA/notifications-api, pull requests merged in 2025-06, with the labels that each got.

#1746 5/30/25 Production Deploy
  .ds.baseline
  .github/actions/setup-project/action.yml
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
  .github/workflows/deploy-demo.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  Makefile
  README.md
  application.py
  docs/all.md
  poetry.lock
  pyproject.toml
Labels: engineering

#1754 Unpin egress proxy release
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
Labels: engineering, github_actions

#1756 Add one more cert environment variable
  manifest.yml
Labels: engineering

#1678 Update Marshmallow and SQLAlchemy dependencies
  .ds.baseline
  Makefile
  app/__init__.py
  app/events/rest.py
  app/job/rest.py
  app/notifications/rest.py
  app/public_schemas/__init__.py
  app/public_schemas/public.py
  app/schemas.py
  app/service/rest.py
  app/service_invite/rest.py
  app/template/rest.py
  app/utils.py
  poetry.lock
  pyproject.toml
  tests/app/notifications/test_rest.py
  tests/app/public_contracts/test_GET_notification.py
  tests/app/service/test_rest.py
  tests/app/test_schemas.py
  tests/app/test_utils.py
Labels: engineering, dependencies

#1776 06/12/25 Production Deploy
  .ds.baseline
  .github/actions/deploy-proxy/action.yml
  .github/actions/setup-project/action.yml
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
  Makefile
  README.md
  app/__init__.py
  app/aws/s3.py
  app/celery/tasks.py
  app/events/rest.py
  app/job/rest.py
  app/notifications/rest.py
  app/notifications/sns_cert_validator.py
  app/public_schemas/__init__.py
  app/public_schemas/public.py
  app/schemas.py
  app/service/rest.py
  app/service_invite/rest.py
  app/status/healthcheck.py
  app/template/rest.py
  app/utils.py
  docs/adrs/0014-adr-localize-notifications-python-client.md
  manifest.yml
  poetry.lock
  pyproject.toml
  tests/app/notifications/test_rest.py
  tests/app/public_contracts/test_GET_notification.py
  tests/app/service/test_rest.py
  tests/app/test_schemas.py
  tests/app/test_utils.py
Labels: engineering

#1805 Production Deploy 06/30/2025
  .github/actions/setup-project/action.yml
  .github/workflows/checks.yml
  .github/workflows/drift.yml
  README.md
  app/authentication/auth.py
  app/commands.py
  app/config_files/templates.json
  app/dao/jobs_dao.py
  app/dao/notifications_dao.py
  app/job/rest.py
  app/notifications/rest.py
  app/organization/invite_rest.py
  app/organization/rest.py
  app/provider_details/rest.py
  app/service/rest.py
  app/service_invite/rest.py
  app/template/rest.py
  app/template_folder/rest.py
  app/template_statistics/rest.py
  app/upload/rest.py
  app/user/rest.py
  app/utils.py
  app/webauthn/rest.py
  notifications_python_client/__init__.py
  notifications_python_client/authentication.py
  notifications_python_client/base.py
  notifications_python_client/errors.py
  notifications_python_client/notifications.py
  notifications_python_client/py.typed
  notifications_python_client/utils.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/app/authentication/test_authentication.py
  tests/app/dao/test_jobs_dao.py
  tests/app/job/test_rest.py
  tests/app/notifications/test_rest.py
  tests/app/service/send_notification/test_send_notification.py
  tests/app/test_utils.py
Labels: engineering
