Repository GSA/notifications-api, pull requests merged in 2025-01, with the labels that each got.

#1510 1/2/2025 Production Deploy
  app/celery/provider_tasks.py
  app/celery/scheduled_tasks.py
  app/celery/tasks.py
  app/clients/cloudwatch/aws_cloudwatch.py
  app/config.py
  app/dao/notifications_dao.py
  app/notifications/process_notifications.py
  app/service_invite/rest.py
  loadtest_10k.csv
  poetry.lock
  pyproject.toml
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/clients/test_aws_cloudwatch.py
  tests/app/dao/notification_dao/test_notification_dao.py
Labels: engineering, python

#1517 1/6/25 Production Deploy
  .github/actions/setup-project/action.yml
  Makefile
  app/aws/s3.py
  poetry.lock
  pyproject.toml
Labels: engineering

#1518 Change delivery receipts tasks time to help UI lag
  app/celery/scheduled_tasks.py
  app/config.py
Labels: engineering

#1519 Update daily_check GitHub Action
  .github/workflows/daily_checks.yml
Labels: engineering, github_actions

#1534 Invite expiration fix
  app/dao/notifications_dao.py
  app/service_invite/rest.py
  tests/app/celery/test_reporting_tasks.py
Labels: engineering

#1536 01/16/2025 Production Deploy
  .github/workflows/daily_checks.yml
  Makefile
  app/__init__.py
  app/celery/scheduled_tasks.py
  app/celery/tasks.py
  app/clients/__init__.py
  app/commands.py
  app/config.py
  app/dao/jobs_dao.py
  app/dao/notifications_dao.py
  app/models.py
  app/notifications/process_notifications.py
  app/service_invite/rest.py
  docs/adrs/0010-adr-celery-pool-support-best-practice.md
  manifest.yml
  notifications_utils/clients/redis/redis_client.py
  tests/app/celery/test_reporting_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/notifications/test_process_notification.py
  tests/app/organization/test_invite_rest.py
  tests/app/service/send_notification/test_send_notification.py
  tests/app/service/test_rest.py
  tests/app/service_invite/test_service_invite_rest.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
Labels: engineering

#1549 Update zaproxy-api-scan GitHub Action reference
  .github/workflows/checks.yml
  .github/workflows/daily_checks.yml
Labels: engineering, github_actions
